backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Website Content"
    files:
      - file: "content/stories.json"
        name: "stories"
        label: "Current Feed Stories"
        fields:
          - name: "entries"
            label: "Story Entries"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - name: "title"
                label: "Title / Day Number (e.g., Day 44)"
                widget: "string"
              - name: "date"
                label: "Publish Date (e.g., June 4, 2026)"
                widget: "datetime"
                date_format: "MMMM DD, YYYY"
                time_format: false
              - name: "body"
                label: "Story Text Block (100-150 words)"
                widget: "text"
